# Generated by Django 5.0.6 on 2024-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_created_at_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("withdrawal", "Withdrawal"), ("deposit", "Deposit")],
                max_length=20,
            ),
        ),
    ]
